Repository andela/rogue-backend, pull requests merged in 2019-09, with the labels that each got.

#45 #167727641 Build out endpoints for availing and approving pending requests
  src/controllers/RequestController.js
  src/middlewares/authorization.js
  src/migrations/03-create-requests.js
  src/models/Request.js
  src/models/User.js
  src/routes/requestRoute.js
  src/seeders/01-demo-user.js
  src/seeders/03-demo-request.js
  src/test/integrationTests/requestController.test.js
Labels: Ready-for-review

#43 #167727640 User(manager) can Reject a Request
  src/controllers/RequestController.js
  src/models/Request.js
  src/models/User.js
  src/routes/requestRoute.js
  src/test/integrationTests/requestController.test.js
  src/test/integrationTests/userController.test.js
  src/test/unitTests/requestController.test.js
  src/utils/ResponseHandler.js
Labels: Ready-to-get-merged

#42 #167727653 Edit Travel Request
  package-lock.json
  package.json
  src/controllers/RequestController.js
  src/migrations/03-create-requests.js
  src/models/Request.js
  src/routes/requestRoute.js
  src/seeders/03-demo-request.js
  src/test/integrationTests/requestController.test.js
Labels: Ready-for-review, Ready-to-get-merged

#41 #167727635 Build multi-city request route
  package.json
  src/config/config.js
  src/controllers/RequestController.js
  src/controllers/UserController.js
  src/migrations/03-create-requests.js
  src/models/Request.js
  src/models/User.js
  src/routes/requestRoute.js
  src/seeders/03-demo-request.js
  src/test/integrationTests/requestController.test.js
  src/validation/index.js
Labels: Ready-for-review

#46 #167727650 Add Search Functionality For Trip Requests
  src/controllers/RequestController.js
  src/middlewares/index.js
  src/middlewares/searchRequestsMiddleware.js
  src/models/User.js
  src/routes/authRoute.js
  src/routes/requestRoute.js
  src/routes/userRoute.js
  src/seeders/03-demo-request.js
  src/test/integrationTests/requestController.test.js
  src/test/unitTests/index.js
  src/test/unitTests/middleware.test.js
  src/test/unitTests/searchRequestsMiddleware.test.js
  src/validation/index.js
  yarn.lock
Labels: Ready-for-review

#29 feature(social Oauth):add social media login route
  package.json
  src/config/passport.js
  src/controllers/UserController.js
  src/controllers/socialController.js
  src/index.js
  src/models/User.js
  src/routes/index.js
  src/routes/socialAuthRoute.js
  src/seeders/01-demo-user.js
  src/test/integrationTests/index.js
  src/test/integrationTests/socialController.test.js
  src/test/integrationTests/userController.test.js
  src/test/unitTests/middleware.test.js
  src/test/unitTests/mockStrategy.js
  src/test/unitTests/requestController.test.js
  src/test/unitTests/sendEmail.test.js
  src/utils/authentication.js
  yarn.lock
Labels: Ready-for-review

#47 #167727662-Re-Confirm-Travel-Requests
  src/controllers/RequestController.js
  src/index.js
  src/migrations/03-create-requests.js
  src/models/Request.js
  src/models/User.js
  src/routes/index.js
  src/routes/requestRoute.js
  src/routes/socialAuthRoute.js
  src/test/integrationTests/requestController.test.js
  src/test/integrationTests/userController.test.js
  src/test/unitTests/requestController.test.js
  src/test/unitTests/sendEmail.test.js
  src/utils/ResponseHandler.js
  src/validation/index.js
Labels: Ready-for-review

#40 sends emails to users for password reset
  .babelrc
  package-lock.json
  src/controllers/UserController.js
  src/routes/userRoute.js
  src/seeders/01-demo-user.js
  src/test/integrationTests/requestController.test.js
  src/test/integrationTests/userController.test.js
  src/test/unitTests/sendEmail.test.js
  src/utils/sendEmail.js
  src/validation/index.js
Labels: help wanted

#48 #167727666 Add request edit notification
  package.json
  src/controllers/NotificationController.js
  src/controllers/RequestController.js
  src/migrations/04-create-notification.js
  src/models/Notification.js
  src/routes/notificationRoute.js
  src/test/integrationTests/requestController.test.js
  src/utils/index.js
  src/utils/notificationHelper.js
  yarn.lock
Labels: Ready-for-review

#60 #167727646 Ensures User Notification on approved Request
  src/controllers/NotificationController.js
  src/controllers/RequestController.js
  src/models/Messages.js
  src/routes/notificationRoute.js
  src/utils/notificationHelper.js
Labels: Ready-for-review, Ready-to-get-merged

#53 #167727671 Like/Unlike An Accommodation Facility
  src/controllers/AccommodationController.js
  src/controllers/UserController.js
  src/controllers/index.js
  src/migrations/04-create-liked-accommodations.js
  src/models/Accommodation.js
  src/models/Likes.js
  src/models/User.js
  src/routes/accommodationRoute.js
  src/routes/index.js
  src/test/integrationTests/accommodationController.test.js
  src/test/integrationTests/index.js
  src/validation/index.js
Labels: Ready-for-review

#62 #167727655 User(requester) should get notification for his edited request
  src/controllers/RequestController.js
  src/utils/notificationHelper.js
  src/utils/sendEmail.js
Labels: Ready-for-review, Ready-to-get-merged

#55 Add the create accomodation facility by the travel Admin
  package.json
  src/controllers/AccommodationController.js
  src/controllers/AccomodationController.js
  src/controllers/UserController.js
  src/middlewares/authorization.js
  src/migrations/01-create-user.js
  src/migrations/02-create-accomodation.js
  src/migrations/05-create-liked-accommodations.js
  src/migrations/06-create-messages.js
  src/models/Accommodation.js
  src/models/User.js
  src/routes/accommodationRoute.js
  src/seeders/01-demo-user.js
  src/test/integrationTests/userController.test.js
  src/test/unitTests/accomodation.test.js
Labels: Ready-for-review
